### ISSUE TITLE
Could not load NIB when installed via CocoaPods.

### ISSUE THREAD

**Issue by szysz3** [dogo/AKMediaViewer#1]
There's an following exception thrown, when library is installed via CocoaPods:

`2016-10-14 08:58:26.134 AKMediaViewerExample[2251:41867] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/.../Library/Developer/CoreSimulator/Devices/DA1F5112-EF4D-4205-ABA2-F66D475C03B2/data/Containers/Bundle/Application/585AF380-D515-401F-BE98-C0DD5412C682/AKMediaViewerExample.app/Frameworks/AKMediaViewer.framework> (loaded)' with name 'AKMediaViewerController''
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ceb334b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109a8521e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010cf1c265 +[NSException raise:format:] + 197
	3   UIKit                               0x000000010b98001a -[UINib instantiateWithOwner:options:] + 507
	4   UIKit                               0x000000010b713ff5 -[UIViewController _loadViewFromNibNamed:bundle:] + 386
	5   UIKit                               0x000000010b714917 -[UIViewController loadView] + 177
	6   UIKit                               0x000000010b714c4c -[UIViewController loadViewIfRequired] + 201
	7   UIKit                               0x000000010b7154a0 -[UIViewController view] + 27
	8   AKMediaViewer                       0x000000010949ef47 _TFC13AKMediaViewer23AKMediaViewerControllercfT7nibNameGSqSS_6bundleGSqCSo6Bundle__S0_ + 1207
	9   AKMediaViewer                       0x000000010949f10d _TFC13AKMediaViewer23AKMediaViewerControllerCfT7nibNameGSqSS_6bundleGSqCSo6Bundle__S0_ + 125
	10  AKMediaViewer                       0x00000001094b09d0 _TFC13AKMediaViewer20AKMediaViewerManager26focusViewControllerForViewfCSo6UIViewGSqCS_23AKMediaViewerController_ + 2560
	11  AKMediaViewer                       0x00000001094b296a _TFC13AKMediaViewer20AKMediaViewerManager17startFocusingViewfCSo6UIViewT_ + 298
	12  AKMediaViewer                       0x00000001094bc5b3 _TFC13AKMediaViewer20AKMediaViewerManager18handleFocusGesturefCSo19UIGestureRecognizerT_ + 163
	13  AKMediaViewer                       0x00000001094bc60a _TToFC13AKMediaViewer20AKMediaViewerManager18handleFocusGesturefCSo19UIGestureRecognizerT_ + 58
	14  UIKit                               0x000000010bab6289 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	15  UIKit                               0x000000010babe028 _UIGestureRecognizerSendTargetActions + 109
	16  UIKit                               0x000000010babbaf7 _UIGestureRecognizerSendActions + 227
	17  UIKit                               0x000000010babad83 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 891
	18  UIKit                               0x000000010baa6e56 _UIGestureEnvironmentUpdate + 1395
	19  UIKit                               0x000000010baa689b -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 521
	20  UIKit                               0x000000010baa5a7e -[UIGestureEnvironment _updateGesturesForEvent:window:] + 286
	21  UIKit                               0x000000010b5e47ad -[UIWindow sendEvent:] + 3989
	22  UIKit                               0x000000010b591a33 -[UIApplication sendEvent:] + 371
	23  UIKit                               0x000000010bd83b6d __dispatchPreprocessedEventFromEventQueue + 3248
	24  UIKit                               0x000000010bd7c817 __handleEventQueue + 4879
	25  CoreFoundation                      0x000000010ce58311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	26  CoreFoundation                      0x000000010ce3d59c __CFRunLoopDoSources0 + 556
	27  CoreFoundation                      0x000000010ce3ca86 __CFRunLoopRun + 918
	28  CoreFoundation                      0x000000010ce3c494 CFRunLoopRunSpecific + 420
	29  GraphicsServices                    0x000000010f003a6f GSEventRunModal + 161
	30  UIKit                               0x000000010b573f34 UIApplicationMain + 159
	31  AKMediaViewerExample                0x00000001093ece4f main + 111
	32  libdyld.dylib                       0x000000010f5eb68d start + 1
)
`

I think that bundle paths have to be changed from:

`viewController = AKMediaViewerController.init(nibName: "AKMediaViewerController", bundle: Bundle(for: AKMediaViewerController.classForCoder()))` 

to 

`let bundlePath = Bundle(for: AKMediaViewerController.self).path(forResource: "AKMediaViewer", ofType: "bundle")
viewController = AKMediaViewerController.init(nibName: "AKMediaViewerController", bundle: Bundle(path: bundlePath!))`

and

`let defaultController: AKMediaFocusBasicToolbarController = AKMediaFocusBasicToolbarController(nibName: "AKMediaFocusBasicToolbar", bundle: Bundle(for: AKMediaFocusBasicToolbarController.classForCoder()))`

to

`let bundlePath = Bundle(for: AKMediaFocusBasicToolbarController.self).path(forResource: "AKMediaViewer", ofType: "bundle")
let defaultController: AKMediaFocusBasicToolbarController = AKMediaFocusBasicToolbarController(nibName: "AKMediaFocusBasicToolbar", bundle: Bundle(path: bundlePath!))`

**Comment by dogo** [comment]
Thanks @szysz3, my bad :P. Please update to 1.01
