### ISSUE TITLE
Crashes with slow internet connection

### ISSUE THREAD

**Issue by Yoloabdo** [dogo/AKMediaViewer#2]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKMediaViewer version: `1.0.0`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. set connection simulator to Edge or 100% loss
 2. play video
 3. crashes

###### Expected Result
loads for longer time
###### Actual Result
app crashes
### Tell us what could be improved:
this needs to be fixed, i'll check it myself and push if got lucky

**Comment by ak1000** [comment]
Unable to replicate.

**Comment by Yoloabdo** [comment]
with streaming url?

**Comment by ak1000** [comment]
yes, but fyi I'm running dev. version of iOS on my i6.  I can try again w/ another build.

**Comment by dogo** [comment]
Fix by @Yoloabdo PR #3
