### ISSUE TITLE
support to swift 2.3

### ISSUE THREAD

**Issue by nelsongc** [dogo/AKMediaViewer#4]
Please give us support to swift 2.3

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - AKMediaViewer version: `0.0.2`
 - Device OS version: `9.3`
 - Device Name: `iPhone 5s`
 
###### Reproduction Steps
 1.
 2.
 3.

**Comment by dogo** [comment]
Hi @nelsongc, sadly there is no plans to support Swift 2.3, I encourage you to migrate to Swift 3.X
