### ISSUE TITLE
imageScrollView.zoomImageView is nil

### ISSUE THREAD

**Issue by nelsongc** [dogo/AKMediaViewer#5]
when try to close the full image give me a error
fatal error: unexpectedly found nil while unwrapping an Optional value
file: AKMediaViewerController.swift

func uninstallZoomView() {
       
        let frame: CGRect = contentView!.convert(imageScrollView.zoomImageView!.frame, from: imageScrollView)
        imageScrollView.isHidden = true
        mainImageView.isHidden = false
        mainImageView.frame = frame
    }

when I check
this line
imageScrollView.zoomImageView is nil

this problem happen when I disable zoom

**Comment by dogo** [comment]
Thanks @nelsongc , I already fixes the issue, please update to 1.0.5
